name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
version: 3.2.3
publish_to: none # todo remove it

dependencies:
  flutter:
    sdk: flutter
  # flutter_cache_manager:
  #   path: ../../flutter_cache_manager/flutter_cache_manager # todo remove it
  octo_image: ^1.0.0
  cached_network_image_platform_interface:
    path: ../cached_network_image_platform_interface # todo remove it
  cached_network_image_web:
    path: ../cached_network_image_web # todo remove it


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  flutter_lints: ^1.0.4
  file: ^6.1.0

environment:
  flutter: ">=3.3.0"
  sdk: ">=2.18.0 <3.0.0"
